# Generated by Django 5.1.2 on 2024-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_title_8f019f_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_objecti_8fdb4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_duratio_798967_idx',
        ),
        migrations.RenameField(
            model_name='historicalproject',
            old_name='duration',
            new_name='actual_duration',
        ),
        migrations.RenameField(
            model_name='historicalproject',
            old_name='objective',
            new_name='actual_objective',
        ),
        migrations.RenameField(
            model_name='historicalproject',
            old_name='title',
            new_name='actual_title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='duration',
            new_name='actual_duration',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='objective',
            new_name='actual_objective',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='actual_title',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='generated_by',
            field=models.CharField(blank=True, choices=[('AI_GENERATED', 'AI_GENERATED'), ('EXPERT_VETTED', 'EXPERT_VETTED')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='program_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='program_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='generated_by',
            field=models.CharField(blank=True, choices=[('AI_GENERATED', 'AI_GENERATED'), ('EXPERT_VETTED', 'EXPERT_VETTED')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='program_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='program_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
