# Generated by Django 5.1.2 on 2024-12-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0002_remove_project_project_title_8f019f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='actual_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='generated_by',
            field=models.CharField(choices=[('AI_GENERATED', 'AI_GENERATED'), ('EXPERT_VETTED', 'EXPERT_VETTED')], default='AI_GENERATED', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='generated_by',
            field=models.CharField(choices=[('AI_GENERATED', 'AI_GENERATED'), ('EXPERT_VETTED', 'EXPERT_VETTED')], default='AI_GENERATED', max_length=100),
        ),
    ]
