# Generated by Django 5.1.2 on 2024-12-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0004_historicaltask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='program_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_id',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='program_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
