# Generated by Django 5.1.2 on 2024-12-19 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_alter_historicalprofile_designation_and_more'),
        ('shikshalokam', '0007_evidence_type_historicalevidence_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('inPROGRESS', 'inPROGRESS'), ('SUBMITTED', 'SUBMITTED'), ('PUBLISHED', 'PUBLISHED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='chatbot.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('inPROGRESS', 'inPROGRESS'), ('SUBMITTED', 'SUBMITTED'), ('PUBLISHED', 'PUBLISHED')], max_length=100, null=True),
        ),
    ]
