# Generated by Django 5.1.2 on 2024-12-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0009_historicalprojectvernacular_projectvernacular'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='program_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='project_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='program_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
