# Generated by Django 5.1.2 on 2025-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0010_historicalproject_program_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
