# Generated by Django 5.1.2 on 2025-01-15 07:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_media_priority_alter_companybot_bot_temperature_and_more'),
        ('shikshalokam', '0011_historicalproject_wishlist_project_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='project',
            name='wishlist',
        ),
        migrations.CreateModel(
            name='HistoricalProjectWishlist',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.project')),
            ],
            options={
                'verbose_name': 'historical project wishlist',
                'verbose_name_plural': 'historical project wishlists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='chatbot.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='shikshalokam.project')),
            ],
            options={
                'db_table': 'shikshalokam"."project_wishlist',
                'indexes': [models.Index(fields=['author'], name='project_wis_author__01388d_idx'), models.Index(fields=['project'], name='project_wis_project_983af9_idx'), models.Index(fields=['created_at'], name='project_wis_created_6951d7_idx')],
            },
        ),
    ]
