# Generated by Django 5.1.2 on 2025-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0012_remove_historicalproject_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='project_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
