# Generated by Django 5.1.2 on 2024-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_chatsession_session_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storymedia',
            name='source_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
