# Generated by Django 5.1.2 on 2024-12-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_story_problem_statement_storymedia_source_path'),
        ('chatbot', '0008_merge_20241206_1208'),
    ]

    operations = [
    ]
