# Generated by Django 5.1.2 on 2024-12-09 08:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_merge_20241206_1719'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMitraProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=400)),
                ('project_id', models.CharField(db_index=True, max_length=400)),
                ('program_id', models.CharField(blank=True, max_length=400, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mitra project',
                'verbose_name_plural': 'historical mitra projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MitraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=400, unique=True)),
                ('project_id', models.CharField(max_length=400, unique=True)),
                ('program_id', models.CharField(blank=True, max_length=400, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'session', 'project_id', 'program_id', 'created_at'], name='chatbot_mit_title_db1b4f_idx')],
            },
        ),
    ]
