# Generated by Django 5.1.2 on 2024-12-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_historicalmitraproject_mitraproject'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mitraproject',
            name='chatbot_mit_title_db1b4f_idx',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='project_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='historicalmitraproject',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.profile'),
        ),
        migrations.AddField(
            model_name='mitraproject',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.profile'),
        ),
        migrations.AddIndex(
            model_name='mitraproject',
            index=models.Index(fields=['title', 'session', 'project_id', 'program_id', 'created_at', 'profile'], name='chatbot_mit_title_d4e3e2_idx'),
        ),
    ]
