# Generated by Django 5.1.2 on 2024-12-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_remove_mitraproject_chatbot_mit_title_db1b4f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='problem_statement',
        ),
    ]
