# Generated by Django 5.1.2 on 2024-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_story_problem_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='userid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
