# Generated by Django 5.1.2 on 2025-02-08 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_story_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='max_token',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='max_token',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
