# Generated by Django 5.1.2 on 2024-12-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_media_keyvalue_mediavector'),
        ('chatbot', '0013_historicalprofile_userid_profile_userid'),
    ]

    operations = [
    ]
