# Generated by Django 5.1.2 on 2024-12-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_merge_20241215_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
