# Generated by Django 5.1.2 on 2025-01-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_alter_media_media_type_alter_storymedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
