# Generated by Django 5.1.2 on 2025-01-10 10:52

import chatbot.models.media_models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_story_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=50),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='bot_temperature',
            field=models.FloatField(default=0, help_text='Set the temperature for controlling response randomness (0-1). Lower values produce more deterministic responses.'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='company',
            field=models.ForeignKey(help_text='Select the company this bot belongs to.', on_delete=django.db.models.deletion.CASCADE, to='chatbot.company'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='context',
            field=models.TextField(help_text="Provide the bot's main prompt or description of its purpose."),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='dynamic_context',
            field=models.TextField(blank=True, help_text="Provide dynamic context that can be adjusted during the bot's interactions, such as personalized data.", null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='end_context',
            field=models.TextField(blank=True, help_text='Provide additional prompt or context to append at the end of the main prompt to guide the conversation', null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='filter_score',
            field=models.FloatField(default=0.8, help_text='Set the filter score for bot response selection (0-1). Responses below this score will be filtered out.'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='introductory_message',
            field=models.CharField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT3.5'), ('gpt-3.5-turbo-16k', 'GPT3.5-16k'), ('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('gpt-3.5-turbo-0125', 'GPT3_5_TURBO_0125'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-3.5-turbo', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='name',
            field=models.CharField(help_text='Enter the name of the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='pre_context',
            field=models.TextField(blank=True, help_text='Provide pre-context that will be set before the main prompt to shape the conversation.', null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='route',
            field=models.CharField(default='/', help_text='Specify the route or API endpoint for interacting with the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='tag_context',
            field=models.TextField(blank=True, help_text='Provide any information or context related to variables (like Python-bound variables) that will be inserted into the prompt.', null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='top_k',
            field=models.IntegerField(default=2, help_text="Set the top-k value for the bot's response selection. This defines how many top options to consider for each response.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='bot_question',
            field=models.TextField(blank=True, help_text='Provide the first question that the bot will ask when the state is triggered.', null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='completion_criteria',
            field=models.TextField(blank=True, help_text='Define the criteria required to move from this state to the next state.', null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='context',
            field=models.TextField(blank=True, help_text='Provide the main prompt or description of the state, explaining its purpose.', null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='name',
            field=models.CharField(help_text='Enter the name of the state.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='step',
            field=models.IntegerField(help_text='Integer representing the order in which state function calling happens. Lower values are called first.'),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='type',
            field=models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('OPTIONAL', 'OPTIONAL')], default='MANDATORY', help_text='Specify whether the state is mandatory or optional.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='bot_temperature',
            field=models.FloatField(default=0, help_text='Set the temperature for controlling response randomness (0-1). Lower values produce more deterministic responses.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select the company this bot belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.company'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='context',
            field=models.TextField(help_text="Provide the bot's main prompt or description of its purpose."),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='dynamic_context',
            field=models.TextField(blank=True, help_text="Provide dynamic context that can be adjusted during the bot's interactions, such as personalized data.", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='end_context',
            field=models.TextField(blank=True, help_text='Provide additional prompt or context to append at the end of the main prompt to guide the conversation', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='filter_score',
            field=models.FloatField(default=0.8, help_text='Set the filter score for bot response selection (0-1). Responses below this score will be filtered out.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='introductory_message',
            field=models.CharField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT3.5'), ('gpt-3.5-turbo-16k', 'GPT3.5-16k'), ('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('gpt-3.5-turbo-0125', 'GPT3_5_TURBO_0125'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-3.5-turbo', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='name',
            field=models.CharField(help_text='Enter the name of the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='pre_context',
            field=models.TextField(blank=True, help_text='Provide pre-context that will be set before the main prompt to shape the conversation.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='route',
            field=models.CharField(default='/', help_text='Specify the route or API endpoint for interacting with the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='tag_context',
            field=models.TextField(blank=True, help_text='Provide any information or context related to variables (like Python-bound variables) that will be inserted into the prompt.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='top_k',
            field=models.IntegerField(default=2, help_text="Set the top-k value for the bot's response selection. This defines how many top options to consider for each response.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(max_length=1000, upload_to=chatbot.models.media_models.Media.get_file_upload_path),
        ),
    ]
