# Generated by Django 5.1.2 on 2025-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_media_priority_alter_companybot_bot_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitraproject',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='abrupt_introductory_message',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='agent_provider',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='retell_agent_id',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='twilio_queue',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='companychat',
            name='source_msg_id',
        ),
        migrations.RemoveField(
            model_name='companychat',
            name='whatsapp_message_id',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='abrupt_introductory_message',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='agent_provider',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='retell_agent_id',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='twilio_queue',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='companychat',
            name='source',
            field=models.CharField(choices=[('WEB', 'WEB'), ('PHONE', 'PHONE')], default='WEB', max_length=20),
        ),
        migrations.DeleteModel(
            name='HistoricalMitraProject',
        ),
        migrations.DeleteModel(
            name='MitraProject',
        ),
    ]
