# Generated by Django 5.1.2 on 2025-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_companybot_max_token_historicalcompanybot_max_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse', 'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='openai', max_length=100),
        ),
        migrations.AddField(
            model_name='companybot',
            name='provider_keys',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse', 'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='openai', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='provider_keys',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('GOOGLE_V1', 'GOOGLE v1 STT'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper')], default='AI4Bharat', max_length=300, null=True),
        ),
    ]
