# Generated by Django 5.1.2 on 2025-02-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_historicalbotvernacular_botvernacular'),
    ]

    operations = [
        migrations.AddField(
            model_name='botvernacular',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the name of the bot.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbotvernacular',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the name of the bot.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='botvernacular',
            name='introductory_message',
            field=models.TextField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', null=True),
        ),
        migrations.AlterField(
            model_name='botvernacular',
            name='language',
            field=models.CharField(help_text='Language code, Example for English use en.', max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalbotvernacular',
            name='introductory_message',
            field=models.TextField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbotvernacular',
            name='language',
            field=models.CharField(help_text='Language code, Example for English use en.', max_length=250),
        ),
    ]
