# Generated by Django 5.1.2 on 2025-02-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_story_blurb'),
        ('chatbot', '0022_botvernacular_name_historicalbotvernacular_name_and_more'),
    ]

    operations = [
    ]
