# Generated by Django 5.1.2 on 2025-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_botvernacular_name_historicalbotvernacular_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botvernacular',
            name='alt_introductory_message',
            field=models.TextField(blank=True, help_text='Provide an alternate introductory message that the bot will present when the conversation starts.', null=True),
        ),
        migrations.AddField(
            model_name='botvernacular',
            name='error_message',
            field=models.TextField(blank=True, help_text='Provide an error message that the bot will display.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbotvernacular',
            name='alt_introductory_message',
            field=models.TextField(blank=True, help_text='Provide an alternate introductory message that the bot will present when the conversation starts.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbotvernacular',
            name='error_message',
            field=models.TextField(blank=True, help_text='Provide an error message that the bot will display.', null=True),
        ),
    ]
