# Generated by Django 5.1.2 on 2025-02-15 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_botvernacular_alt_introductory_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybot',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='language',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='provider_code',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='sample_link',
        ),
        migrations.AddField(
            model_name='companybot',
            name='max_token',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='companybot',
            name='tool_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='max_token',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='tool_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='validation_logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='company_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='voice',
            name='type',
            field=models.CharField(blank=True, choices=[('SpeechToText', 'Speech To Text'), ('TextToText', 'Text To Text'), ('TextToSpeech', 'Text To Speech')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['company_bot'], name='chatbot_voi_company_9292a4_idx'),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['created_at'], name='chatbot_voi_created_d21d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['type'], name='chatbot_voi_type_98349d_idx'),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['provider'], name='chatbot_voi_provide_b4b230_idx'),
        ),
    ]
