# Generated by Django 5.1.2 on 2025-02-17 10:13

import chatbot.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_remove_companybot_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=chatbot.models.base_models.Company.get_file_upload_path),
        ),
    ]
