# Generated by Django 5.1.2 on 2025-08-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0046_chatsession_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(related_name='medias', to='chatbot.tag'),
        ),
    ]
