# Generated by Django 5.1.2 on 2025-08-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0047_media_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Global Tag', 'verbose_name_plural': 'Global Tags'},
        ),
        migrations.AddField(
            model_name='media',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
