# Generated by Django 5.1.2 on 2025-08-18 10:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0048_alter_tag_options_media_extracted_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='media',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('extracted_text', config='english'), name='media_extracted_text_gin'),
        ),
    ]
