# Generated by Django 5.1.2 on 2025-11-10 15:19

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0065_story_block_story_district_story_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(help_text='Name of the flow.', max_length=255)),
                ('flow_route', models.CharField(help_text='Route/path for accessing this flow.', max_length=255)),
                ('languages', models.JSONField(default=list, help_text="List of supported language codes (e.g., ['en', 'hi', 'kn']).")),
                ('hidden', models.BooleanField(default=False, help_text='If True, this flow will be hidden from public listing.')),
                ('active', models.BooleanField(default=True, help_text='If False, this flow will be disabled and not accessible.')),
                ('allow_image_upload', models.BooleanField(default=False, help_text='Allow users to upload images in this flow.')),
                ('websocket_url', models.URLField(blank=True, help_text='WebSocket URL for real-time communication (optional).', max_length=500, null=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types allowed to access this flow (guest, auth, or all).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_id', models.ForeignKey(help_text='The main bot associated with this flow.', on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='chatbot.companybot')),
                ('parent_flow_id', models.ForeignKey(blank=True, help_text='Parent flow if this is a sub-flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_flows', to='chatbot.flow')),
                ('story_bot_id', models.ForeignKey(blank=True, help_text='Optional secondary bot for story-related functionality.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_flows', to='chatbot.companybot')),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
            },
        ),
        migrations.CreateModel(
            name='ImageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this image configuration.', max_length=100)),
                ('max_images', models.IntegerField(default=1, help_text='Maximum number of images allowed.', validators=[django.core.validators.MinValueValidator(0)])),
                ('image_size', models.IntegerField(default=5242880, help_text='Maximum image size in bytes (default: 5MB).', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Configuration',
                'verbose_name_plural': 'Image Configurations',
                'indexes': [models.Index(fields=['name'], name='chatbot_ima_name_1525db_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFlow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('flow_name', models.CharField(help_text='Name of the flow.', max_length=255)),
                ('flow_route', models.CharField(help_text='Route/path for accessing this flow.', max_length=255)),
                ('languages', models.JSONField(default=list, help_text="List of supported language codes (e.g., ['en', 'hi', 'kn']).")),
                ('hidden', models.BooleanField(default=False, help_text='If True, this flow will be hidden from public listing.')),
                ('active', models.BooleanField(default=True, help_text='If False, this flow will be disabled and not accessible.')),
                ('allow_image_upload', models.BooleanField(default=False, help_text='Allow users to upload images in this flow.')),
                ('websocket_url', models.URLField(blank=True, help_text='WebSocket URL for real-time communication (optional).', max_length=500, null=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types allowed to access this flow (guest, auth, or all).', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bot_id', models.ForeignKey(blank=True, db_constraint=False, help_text='The main bot associated with this flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_flow_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent flow if this is a sub-flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow')),
                ('story_bot_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional secondary bot for story-related functionality.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('image_config_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Image configuration settings for this flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.imageconfiguration')),
            ],
            options={
                'verbose_name': 'historical Flow',
                'verbose_name_plural': 'historical Flows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='flow',
            name='image_config_id',
            field=models.ForeignKey(blank=True, help_text='Image configuration settings for this flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='chatbot.imageconfiguration'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['flow_route'], name='chatbot_flo_flow_ro_f6fbff_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['bot_id'], name='chatbot_flo_bot_id__f110e9_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['active'], name='chatbot_flo_active_a1007c_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['hidden'], name='chatbot_flo_hidden_55cd22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('flow_route', 'bot_id')},
        ),
    ]
