# Generated by Django 5.1.2 on 2025-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0066_flow_imageconfiguration_historicalflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='strategy',
            field=models.CharField(blank=True, help_text='Define the strategy or approach this bot uses for conversations.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='language_operation',
            field=models.CharField(choices=[('translate', 'Translate'), ('transliterate', 'Transliterate')], default='translate', help_text='Choose the language operation: Translate (convert meaning) or Transliterate (convert script).', max_length=20),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='operation_type',
            field=models.CharField(choices=[('llm', 'LLM'), ('non_llm', 'Non-LLM')], default='llm', help_text='Choose whether this state uses LLM or non-LLM processing.', max_length=20),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='skip_if_authenticated',
            field=models.BooleanField(default=False, help_text='If True, this state will be skipped for authenticated users.'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='strategy',
            field=models.CharField(blank=True, help_text='Define the strategy or approach this bot uses for conversations.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='language_operation',
            field=models.CharField(choices=[('translate', 'Translate'), ('transliterate', 'Transliterate')], default='translate', help_text='Choose the language operation: Translate (convert meaning) or Transliterate (convert script).', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='operation_type',
            field=models.CharField(choices=[('llm', 'LLM'), ('non_llm', 'Non-LLM')], default='llm', help_text='Choose whether this state uses LLM or non-LLM processing.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='skip_if_authenticated',
            field=models.BooleanField(default=False, help_text='If True, this state will be skipped for authenticated users.'),
        ),
    ]
