# Generated by Django 5.1.2 on 2025-11-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0067_companybot_strategy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='allow_image_upload',
        ),
        migrations.RemoveField(
            model_name='historicalflow',
            name='allow_image_upload',
        ),
    ]
