# Generated by Django 5.1.2 on 2025-11-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0068_remove_flow_allow_image_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(help_text='Template content for PDF generation (e.g., HTML, EJS template).')),
                ('template_name', models.CharField(help_text='Unique name identifier for this template.', max_length=255, unique=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types that can use this template (guest, auth, or all).', max_length=20)),
                ('constants_json', models.JSONField(blank=True, help_text='JSON object containing constants/variables used in the template.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF Template',
                'verbose_name_plural': 'PDF Templates',
                'indexes': [
                    models.Index(fields=['template_name'], name='chatbot_pdf_templat_7b12a7_idx'),
                    models.Index(fields=['user_type'], name='chatbot_pdf_user_ty_8f5c3d_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='template_id',
            field=models.ForeignKey(blank=True, help_text='PDF template for generating documents in this flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='chatbot.pdftemplates'),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='template_id',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='PDF template for generating documents in this flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.pdftemplates'),
        ),
        migrations.CreateModel(
            name='HistoricalPDFTemplates',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('template', models.TextField(help_text='Template content for PDF generation (e.g., HTML, EJS template).')),
                ('template_name', models.CharField(db_index=True, help_text='Unique name identifier for this template.', max_length=255)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types that can use this template (guest, auth, or all).', max_length=20)),
                ('constants_json', models.JSONField(blank=True, help_text='JSON object containing constants/variables used in the template.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
            ],
            options={
                'verbose_name': 'historical PDF Template',
                'verbose_name_plural': 'historical PDF Templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
    ]
