# Generated by Django 5.1.2 on 2025-11-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0069_pdftemplates_flow_template_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='I18nTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text="Unique tag name for grouping translations (e.g., 'welcome_message', 'button_labels').", max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'I18n Tag',
                'verbose_name_plural': 'I18n Tags',
                'ordering': ['tag_name'],
                'indexes': [
                    models.Index(fields=['tag_name'], name='chatbot_i18_tag_nam_a8f3d2_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='HistoricalI18nTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, help_text="Unique tag name for grouping translations (e.g., 'welcome_message', 'button_labels').", max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
            ],
            options={
                'verbose_name': 'historical I18n Tag',
                'verbose_name_plural': 'historical I18n Tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
        migrations.CreateModel(
            name='I18nTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(help_text="Variable name for this translation (e.g., 'title', 'description', 'button_text').", max_length=255)),
                ('language', models.CharField(help_text="Language code (e.g., 'en', 'hi', 'kn', 'te').", max_length=10)),
                ('value', models.TextField(help_text='Translated text value for this variable in the specified language.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_id', models.ForeignKey(help_text='The tag this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chatbot.i18ntag')),
            ],
            options={
                'verbose_name': 'I18n Translation',
                'verbose_name_plural': 'I18n Translations',
                'ordering': ['tag_id', 'variable_name', 'language'],
                'indexes': [
                    models.Index(fields=['tag_id', 'variable_name', 'language'], name='chatbot_i18_tag_id_8b4e7c_idx'),
                    models.Index(fields=['language'], name='chatbot_i18_languag_f2a1b9_idx'),
                    models.Index(fields=['variable_name'], name='chatbot_i18_variabl_d3c5e8_idx'),
                ],
                'unique_together': {('tag_id', 'variable_name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalI18nTranslation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('variable_name', models.CharField(help_text="Variable name for this translation (e.g., 'title', 'description', 'button_text').", max_length=255)),
                ('language', models.CharField(help_text="Language code (e.g., 'en', 'hi', 'kn', 'te').", max_length=10)),
                ('value', models.TextField(help_text='Translated text value for this variable in the specified language.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
                ('tag_id', models.ForeignKey(blank=True, db_constraint=False, help_text='The tag this translation belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.i18ntag')),
            ],
            options={
                'verbose_name': 'historical I18n Translation',
                'verbose_name_plural': 'historical I18n Translations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
    ]
