# Generated by Django 5.1.2 on 2025-11-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0070_i18ntag_historicali18ntag_i18ntranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybot',
            name='strategy',
            field=models.CharField(blank=True, choices=[('oneshot', 'One Shot'), ('guided_guest', 'Guided Guest'), ('guest_discussion', 'Guest Discussion'), ('common', 'Common')], help_text='Select the strategy or approach this bot uses for conversations.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='strategy',
            field=models.CharField(blank=True, choices=[('oneshot', 'One Shot'), ('guided_guest', 'Guided Guest'), ('guest_discussion', 'Guest Discussion'), ('common', 'Common')], help_text='Select the strategy or approach this bot uses for conversations.', max_length=100, null=True),
        ),
    ]
