# Generated by Django 5.1.2 on 2025-11-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0066_alter_botvernacular_unique_together_and_more'),
        ('chatbot', '0071_alter_companybot_strategy_and_more'),
    ]

    operations = [
    ]
