# Generated by Django 5.1.2 on 2025-11-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0072_merge_20251114_1436'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='i18ntag',
            new_name='chatbot_i18_tag_nam_80094f_idx',
            old_name='chatbot_i18_tag_nam_a8f3d2_idx',
        ),
        migrations.RenameIndex(
            model_name='i18ntranslation',
            new_name='chatbot_i18_tag_id__7eb096_idx',
            old_name='chatbot_i18_tag_id_8b4e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='i18ntranslation',
            new_name='chatbot_i18_languag_e2489a_idx',
            old_name='chatbot_i18_languag_f2a1b9_idx',
        ),
        migrations.RenameIndex(
            model_name='i18ntranslation',
            new_name='chatbot_i18_variabl_04d419_idx',
            old_name='chatbot_i18_variabl_d3c5e8_idx',
        ),
        migrations.RenameIndex(
            model_name='pdftemplates',
            new_name='chatbot_pdf_templat_b240ab_idx',
            old_name='chatbot_pdf_templat_7b12a7_idx',
        ),
        migrations.RenameIndex(
            model_name='pdftemplates',
            new_name='chatbot_pdf_user_ty_3368e4_idx',
            old_name='chatbot_pdf_user_ty_8f5c3d_idx',
        ),
    ]
