# Generated by Django 5.1.2 on 2025-11-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0073_rename_chatbot_i18_tag_nam_a8f3d2_idx_chatbot_i18_tag_nam_80094f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystatemachine',
            name='language_operation',
        ),
        migrations.RemoveField(
            model_name='historicalcompanystatemachine',
            name='language_operation',
        ),
    ]
