# Generated by Django 5.2 on 2026-03-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0079_alter_companybot_llm_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companychat',
            name='file_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
