# Generated by Django 5.2 on 2026-03-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0080_alter_companychat_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companychat',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
