# Generated by Django 5.2.12 on 2026-06-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0081_alter_chatsession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='default_flow',
            field=models.ForeignKey(blank=True, help_text='Default child flow shown when this is a parent flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_flows', to='chatbot.flow'),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='default_flow',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Default child flow shown when this is a parent flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalvoice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
    ]
