# Generated by Django 5.2 on 2026-06-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0081_alter_chatsession_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalvoice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
    ]
