# Generated by Django 5.2 on 2026-06-25 12:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0082_flow_default_flow_historicalflow_default_flow_and_more'),
        ('shikshalokam', '0006_add_program_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpdftemplates',
            name='tag',
            field=models.CharField(blank=True, help_text='Report classification tag (e.g., mi-story, discussion-report).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdftemplates',
            name='tag',
            field=models.CharField(blank=True, help_text='Report classification tag (e.g., mi-story, discussion-report).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='shikshalokam.program'),
        ),
        migrations.AddField(
            model_name='story',
            name='village',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalLeaderCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Leader Category',
                'verbose_name_plural': 'historical Leader Categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeaderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leader Category',
                'verbose_name_plural': 'Leader Categories',
                'indexes': [models.Index(fields=['code'], name='chatbot_lea_code_c98eae_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompanyBotProgramMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_bot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.program')),
                ('leader_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.leadercategory')),
            ],
            options={
                'verbose_name': 'historical company bot program mapping',
                'verbose_name_plural': 'historical company bot program mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='story',
            name='leader_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='chatbot.leadercategory'),
        ),
        migrations.CreateModel(
            name='CompanyBotProgramMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_mappings', to='chatbot.companybot')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_mappings', to='shikshalokam.program')),
                ('leader_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_mappings', to='chatbot.leadercategory')),
            ],
            options={
                'indexes': [models.Index(fields=['company_bot'], name='chatbot_com_company_cc3663_idx'), models.Index(fields=['state'], name='chatbot_com_state_8e1646_idx'), models.Index(fields=['program'], name='chatbot_com_program_014931_idx'), models.Index(fields=['leader_category'], name='chatbot_com_leader__f47856_idx'), models.Index(fields=['is_active'], name='chatbot_com_is_acti_be3968_idx')],
                'unique_together': {('company_bot', 'state')},
            },
        ),
    ]
