# Generated by Django 5.2 on 2026-08-13 06:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0082_alter_chatsession_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='default_flow',
            field=models.ForeignKey(blank=True, help_text='Default child flow shown when this is a parent flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_flows', to='chatbot.flow'),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='default_flow',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Default child flow shown when this is a parent flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow'),
        ),
        migrations.AddField(
            model_name='historicalpdftemplates',
            name='tag',
            field=models.CharField(blank=True, help_text='Report classification tag (e.g., mi-story, discussion-report).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdftemplates',
            name='tag',
            field=models.CharField(blank=True, help_text='Report classification tag (e.g., mi-story, discussion-report).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='village',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4.1', 'GPT4_1'), ('gpt-4.1-mini', 'GPT4_1-MINI'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('meta.llama3-70b-instruct-v1:0', 'LLAMA_3_70B_INSTRUCT_COMMON'), ('ap.meta.llama3-70b-instruct-v1:0', 'LLAMA_3_70B_INSTRUCT_AP'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct'), ('gpt-5.2', 'GPT_5_2'), ('gpt-5.2-pro', 'GPT_5_2_PRO'), ('gpt-5-mini', 'GPT_5_MINI')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4.1', 'GPT4_1'), ('gpt-4.1-mini', 'GPT4_1-MINI'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('meta.llama3-70b-instruct-v1:0', 'LLAMA_3_70B_INSTRUCT_COMMON'), ('ap.meta.llama3-70b-instruct-v1:0', 'LLAMA_3_70B_INSTRUCT_AP'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct'), ('gpt-5.2', 'GPT_5_2'), ('gpt-5.2-pro', 'GPT_5_2_PRO'), ('gpt-5-mini', 'GPT_5_MINI')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalvoice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM'), ('ShikshaLokam', 'ShikshaLokam')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM'), ('ShikshaLokam', 'ShikshaLokam')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalLeaderCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Leader Category',
                'verbose_name_plural': 'historical Leader Categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProgram',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('program_uuid', models.CharField(db_index=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical program',
                'verbose_name_plural': 'historical programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Role',
                'verbose_name_plural': 'historical Roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeaderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leader Category',
                'verbose_name_plural': 'Leader Categories',
                'indexes': [models.Index(fields=['code'], name='chatbot_lea_code_c98eae_idx')],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='leader_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='chatbot.leadercategory'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_uuid', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCompanyBotProgramMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_bot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leader_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.leadercategory')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.program')),
            ],
            options={
                'verbose_name': 'historical company bot program mapping',
                'verbose_name_plural': 'historical company bot program mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyBotProgramMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_mappings', to='chatbot.companybot')),
                ('leader_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_mappings', to='chatbot.leadercategory')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_mappings', to='chatbot.program')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='chatbot.program'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'indexes': [models.Index(fields=['code'], name='chatbot_rol_code_4b884d_idx')],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='chatbot.role'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['program_uuid'], name='chatbot_pro_program_9d9786_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='chatbot_pro_name_169b56_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['created_at'], name='chatbot_pro_created_3d5657_idx'),
        ),
        migrations.AddIndex(
            model_name='companybotprogrammapping',
            index=models.Index(fields=['company_bot'], name='chatbot_com_company_cc3663_idx'),
        ),
        migrations.AddIndex(
            model_name='companybotprogrammapping',
            index=models.Index(fields=['state'], name='chatbot_com_state_8e1646_idx'),
        ),
        migrations.AddIndex(
            model_name='companybotprogrammapping',
            index=models.Index(fields=['program'], name='chatbot_com_program_014931_idx'),
        ),
        migrations.AddIndex(
            model_name='companybotprogrammapping',
            index=models.Index(fields=['leader_category'], name='chatbot_com_leader__f47856_idx'),
        ),
        migrations.AddIndex(
            model_name='companybotprogrammapping',
            index=models.Index(fields=['is_active'], name='chatbot_com_is_acti_be3968_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companybotprogrammapping',
            unique_together={('company_bot', 'state')},
        ),
    ]
