# Generated by Django 5.2 on 2026-08-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0083_flow_default_flow_historicalflow_default_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='default_role',
            field=models.ForeignKey(blank=True, help_text='Role applied to reports from this bot when the conversation does not yield one. Leave empty for bots whose reports should not be tagged with a role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_bots', to='chatbot.role'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='default_role',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Role applied to reports from this bot when the conversation does not yield one. Leave empty for bots whose reports should not be tagged with a role.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.role'),
        ),
    ]
