# Generated by Django 5.2 on 2026-08-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0082_alter_chatsession_language_and_more'),
        ('chatbot', '0084_historicalrole_role_story_role'),
    ]

    operations = [
    ]
