# Generated by Django 5.2 on 2026-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0085_seed_chaupal_default_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='report_type',
            field=models.CharField(blank=True, choices=[('mi-story', 'MI Report'), ('discussion-report', 'Discussion Report')], db_index=True, help_text="Report classification, derived from the PDF template of the story's flow.", max_length=50, null=True),
        ),
    ]
