# Generated by Django 5.2 on 2026-08-16 20:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0087_backfill_story_report_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_role_name_ci'),
        ),
    ]
