# Generated by Django 5.2 on 2026-08-17 04:20

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0088_role_unique_role_name_ci'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leadercategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_leader_category_name_ci'),
        ),
    ]
