# Generated by Django 5.2 on 2026-08-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0083_companyStatemachine_translations'),
        ('chatbot', '0090_alter_companybot_llm_model_and_more'),
    ]

    operations = [
    ]
