# Generated by Django 5.2 on 2026-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0091_merge_20260820_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil'), ('pa', 'Punjabi'), ('bn', 'Bengali')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil'), ('pa', 'Punjabi'), ('bn', 'Bengali')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil'), ('pa', 'Punjabi'), ('bn', 'Bengali')], max_length=10),
        ),
    ]
