# Generated by Django 5.2 on 2026-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0094_alter_historicalprogram_name_alter_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil'), ('pa', 'Punjabi'), ('bn', 'Bengali'), ('mr', 'Marathi')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil'), ('pa', 'Punjabi'), ('bn', 'Bengali'), ('mr', 'Marathi')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil'), ('pa', 'Punjabi'), ('bn', 'Bengali'), ('mr', 'Marathi')], max_length=10),
        ),
    ]
