"""
Django settings for Mohini project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import re
import json
from pathlib import Path
from datetime import timedelta
import sentry_sdk
from dotenv import load_dotenv


from django.core.exceptions import ImproperlyConfigured


load_dotenv()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Define the directory for log files
LOGGING_DIR = BASE_DIR + '/shikshalokam_mohini/logs'

with open(BASE_DIR + "/shikshalokam_mohini/config/secrets.json") as f:
    secret = json.loads(f.read())


def get_secret(setting, secrets=secret):
    """
    Get the secret variable or return explicit exception.
    :param setting: The Key of the setting
    :param secrets: The secret.json file

    """
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {0} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#7!xudzh7f@!yih9^l5d)my*$7=^j-@i#qla(k1mae5u(qs_c^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv('SETTINGS_DEBUG') == 'True' else False

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin'
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:9000',
    'https://*.gritworks.ai',
    'https://*.retellai.com',
    'https://gritworks.ai',
    'https://*.vercel.app',
    'https://demo.karnataka.gov.in',
    'https://eitbt.karnataka.gov.in'
]

CORS_ALLOWED_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS'  # Include the OPTIONS method for preflight requests
]

ALLOWED_HOSTS = [
    'localhost',
    '.gritworks.ai',
    '.retellai.com',
    'gritworks.ai',
    '.vercel.app',
    '.demo.karnataka.gov.in',
    '.eitbt.karnataka.gov.in'
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'chatbot',
    'shikshalokam',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'django_extensions',
    'rest_framework',
    'corsheaders',
    'django_countries',
    'django_s3_storage',
    'import_export',
    'simple_history',
]
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'shikshalokam_mohini.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shikshalokam_mohini.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
        'OPTIONS': {
            'sslmode': os.getenv('PG_SSL_MODE'),
            'sslrootcert': os.getenv('PG_SSL_ROOT_CERT')
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = "/var/www/gritworks.ai/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = 'shikshalokam_mohini.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
            "channel_capacity": {
                "http.request": 20000,
                "http.response!*": 20000,
                re.compile(r"^websocket.send\!.+"): 40000,
            }
        },
    },
}

# TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

CSRF_TRUSTED_ORIGINS = ['https://*.gritworks.ai', 'https://*.127.0.0.1', 'https://*.65.1.97.8']

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS Configurations
AWS_REGION = 'ap-south-1'
AWS_ACCESS_KEY_ID = 'AKIARXEET4VKKMHTXQES'
AWS_SECRET_ACCESS_KEY = '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'

AWS_S3_BUCKET_NAME = 'root-media-uploads'
AWS_STORAGE_BUCKET_NAME = 'static-media.gritworks.ai'

JAZZMIN_SETTINGS = {
    'site_title': 'Gritworks',
    'site_header': 'Gritworks',
    'site_brand': 'Gritworks',
    'site_logo': 'public/only_logo.svg',
    'login_logo': 'public/group-11.svg',
    'site_logo_classes': 'img-fluid',
    'welcome_sign': '',
    'copyright': 'Gritworks Pvt Ltd',
    'show_ui_builder': False,
    'changeform_format': 'single',

}

JAZZMIN_UI_TWEAKS = {
    'navbar_fixed': True
}

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_SERIALIZER': 'chatbot.serializers.ProfileTokenObtainPairSerializer'
}

SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = None


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'debug.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 7,     # Keep 7 backup copies
            'formatter': 'verbose',
        },
        'info_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'info.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 7,     # Keep 7 backup copies
            'formatter': 'verbose',
        },
        'warning_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'error.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 7,     # Keep 7 backup copies
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'error.log'),
            'when': 'midnight',  # Rotate daily
            'interval': 1,        # 1 day interval
            'backupCount': 7,     # Keep 7 backup copies
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['debug_file', 'info_file', 'warning_file', 'error_file'],
            'level': os.getenv('DEFAULT_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
}


sentry_sdk.init(
    dsn=os.getenv('SENTRY_DSN'),
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=1.0,
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=1.0,
)

